Added error checking to rebuild script
Former-commit-id: d3b3a89dc5f4a426853c2c8efbd08da35d345f4d
Former-commit-id: adc1f83bdab2ab3167ee63ad90f091797aa69109

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -1,8 +1,25 @@
 #!/bin/bash
 
-./qrc
+function error()
+{
+    echo
+    echo Error on line $1
+    set -- $BASH_COMMAND
+    if ! which $1 2>&1 > /dev/null 
+    then
+        echo Could not find command $1
+    fi
+    echo "Command \"$BASH_COMMAND\" failed"
+    exit 1
+}
+
+trap 'error $LINENO $0' ERR
+
+./qrc ana dsf
 qmake
 make clean
 lrelease ebe.pro
 make
 sudo cp ebe *.qm /usr/bin
+echo " "
+echo ebe is now ready.  Type in \"ebe\" to run the program.
